# Generated by Django 3.2.4 on 2021-07-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Usuario')),
                ('Nombre', models.CharField(max_length=6, verbose_name='Nombre')),
                ('Correo', models.CharField(max_length=20, verbose_name='Email')),
                ('Contraseña', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contraseña')),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
