# Generated by Django 3.2.4 on 2021-07-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_categoriausuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriausuario',
            name='iddCategoria',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id de Categoria'),
        ),
    ]
