# Generated by Django 3.1.7 on 2021-07-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_automovil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automovil',
            name='id',
        ),
        migrations.AlterField(
            model_name='automovil',
            name='patente',
            field=models.CharField(max_length=18, primary_key=True, serialize=False, unique=True),
        ),
    ]
