# Generated by Django 3.1.7 on 2021-07-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210707_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='idUsuario',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Correo',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Email'),
        ),
    ]
