# Generated by Django 3.1.7 on 2021-07-08 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210707_1431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Automovil',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contrasena'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=6, verbose_name='Nombre'),
        ),
    ]
