# Generated by Django 3.1.7 on 2021-07-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210707_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('idAtencion', models.IntegerField(primary_key=True, serialize=False, verbose_name='idAtencion')),
                ('diagnostico', models.CharField(max_length=100)),
                ('mecanico', models.CharField(max_length=25)),
                ('fecha', models.DateField()),
                ('materiales', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='automoviles')),
            ],
        ),
    ]
